apiVersion: numaplane.numaproj.io/v1alpha1
kind: MonoVertexRollout
metadata:
  name: my-monovertex
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  strategy:
    progressive:
      assessmentSchedule: "10,200,60,10"
    analysis:
      templates:
      - templateName: mvtx-acknowledged-messages
        clusterScope: false
    pauseResume:
      fastResume: true
  monoVertex:
    metadata:
      annotations:
        "numaflow.numaproj.io/allowed-resume-strategies": "slow, fast"
    spec:
      source:
        udsource:
          container:
            # image: quay.io/numaio/numaflow-java/source-simple-source:stable
            image: quay.io/numaio/numaflow-java/source-simple-source:bad-image
            # image: quay.io/numaio/numaflow-go/source-simple-source:stable
        # transformer is an optional container to do any transformation to the incoming data before passing to the sink
        transformer:
          container:
            image: quay.io/numaio/numaflow-rs/source-transformer-now:stable
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-java/simple-sink:stable
      scale:
        min: 1
        max: 1