apiVersion: numaplane.numaproj.io/v1alpha1
kind: PipelineRollout
metadata:
  name: my-pipeline
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  pipeline:
    spec:
      interStepBufferServiceName: my-isbsvc
      vertices:
        - name: in
          source:
            # A self data generating source
            generator:
              rpu: 500
              duration: 1s
        # - name: cat
        #   udf:
        #     builtin:
        #       name: cat # A built-in UDF which simply cats the message
        - name: out
          sink:
            # A simple log printing sink
            log: {}
      edges:
        - from: in
        #   to: cat
        # - from: cat
          to: out
        # - from: bad
        #   to: edge