apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ged-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dpadhiar/ged24-demo.git
    targetRevision: HEAD
    path: resources/ged-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true